##########################################################################
monitor = eDP-1, 2560x1600, 0x0 ,1
monitor = HDMI-A-1, preferred, auto, 1, mirror, eDP-1
##########################################################################
input {
      kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1
    sensitivity = -0.2# -1.0 - 1.0, 0 means no modification.
    accel_profile = flat
    touchpad {
        natural_scroll = true
        disable_while_typing = true
    }
    numlock_by_default = true
}
gestures {
    workspace_swipe = true
    workspace_swipe_distance = 100
    workspace_swipe_create_new = true
}
##########################################################################
